# Separate DB for analytics demo
spring.datasource.url=jdbc:postgresql://localhost:5432/jgaffer_test_analytics
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false