export const CRESTS: Record<string, string> = {
  // Premier League
  Arsenal: '/images/PremierLeague/Arsenal.png',
  'Aston Villa': '/images/PremierLeague/Aston-Villa.png',
  Bournemouth: '/images/PremierLeague/Bournemouth.png',
  Brentford: '/images/PremierLeague/Brentford.png',
  Brighton: '/images/PremierLeague/Brighton.png',
  Chelsea: '/images/PremierLeague/Chelsea.png',
  'Crystal Palace': '/images/PremierLeague/Crystal-Palace.png',
  Everton: '/images/PremierLeague/Everton.png',
  Fulham: '/images/PremierLeague/Fulham.png',
  Liverpool: '/images/PremierLeague/Liverpool.png',
  'Manchester City': '/images/PremierLeague/Man-City.png',
  'Manchester United': '/images/PremierLeague/Man-United.png',
  'Newcastle United': '/images/PremierLeague/Newcastle.png',
  'Nottingham Forest': '/images/PremierLeague/Nottingham-Forest.png',
  'Tottenham Hotspur': '/images/PremierLeague/Tottenham.png',
  'West Ham United': '/images/PremierLeague/WestHam.png',
  Wolves: '/images/PremierLeague/Wolves.png',
  'Leicester City': '/images/PremierLeague/Leicester.png',
  'Ipswich Town': '/images/PremierLeague/Ipswich.png',
  Southampton: '/images/PremierLeague/Southampton.png',

  // Serie A — all using /thumb/ PNG renders for reliability
  Atalanta:       '/images/SerieA/Atalanta.png',
  Bologna:        '/images/SerieA/Bologna.png',
  Cagliari:       '/images/SerieA/Cagliari.png',
  Como:           '/images/SerieA/Como.png',
  Empoli:         '/images/SerieA/Empoli.png',
  Fiorentina:     '/images/SerieA/Fiorentina.png',
  Genoa:          '/images/SerieA/Genoa.png',
  'Hellas Verona':'/images/SerieA/Hellas-Verona.png',
  'Inter Milan':  '/images/SerieA/Inter-Milan.png',
  Juventus:       '/images/SerieA/Juventus.png',
  Lazio:          '/images/SerieA/Lazio.png',
  Lecce:          '/images/SerieA/Lecce.png',
  'AC Milan':     '/images/SerieA/AC-Milan.png',
  Monza:          '/images/SerieA/Monza.png',
  Napoli:         '/images/SerieA/Napoli.png',
  Parma:          '/images/SerieA/Parma.png',
  Roma:           '/images/SerieA/Roma.png',
  Torino:         '/images/SerieA/Torino.png',
  Udinese:        '/images/SerieA/Udinese.png',
  Venezia:        '/images/SerieA/Venezia.png',
};
