/** Maps 3-letter match codes → full team names (used to display fixtures) */
export const TEAM_CODES: Record<string, string> = {
  // Premier League
  ARS: 'Arsenal',
  AVL: 'Aston Villa',
  BOU: 'Bournemouth',
  BRE: 'Brentford',
  BHA: 'Brighton',
  CHE: 'Chelsea',
  CRY: 'Crystal Palace',
  EVE: 'Everton',
  FUL: 'Fulham',
  IPS: 'Ipswich Town',
  LEI: 'Leicester City',
  LIV: 'Liverpool',
  MCI: 'Man City',
  MUN: 'Man United',
  NEW: 'Newcastle',
  NFO: 'Nott\'m Forest',
  SOU: 'Southampton',
  TOT: 'Tottenham',
  WHU: 'West Ham',
  WOL: 'Wolves',

  // Serie A
  ATA: 'Atalanta',
  BOL: 'Bologna',
  CAG: 'Cagliari',
  COM: 'Como',
  EMP: 'Empoli',
  FIO: 'Fiorentina',
  GEN: 'Genoa',
  INT: 'Inter Milan',
  JUV: 'Juventus',
  LAZ: 'Lazio',
  LEC: 'Lecce',
  MIL: 'AC Milan',
  MON: 'Monza',
  NAP: 'Napoli',
  PAR: 'Parma',
  ROM: 'Roma',
  TOR: 'Torino',
  UDI: 'Udinese',
  VEN: 'Venezia',
  VER: 'Hellas Verona',
};
